@token=eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImQyZWExZGZjLWE2ODMtNDA3My05OWFjLTQ2MTQ0MDUzM2I3MSIsImlhdCI6MTc1MDg3NDg5Mywic3ViIjoidG9rZW4ifQ.LaeIICBkX5JPXKumGFDxFDIkCG4AKXNa2RvPpUeqYuM
@playerId=cmclwzqj800019kgd9hux8x0p
@tournamentId=cmcn6z3hr00009kjz9gp9fq48

### 
# @name GET playes 
GET {{NEXT_PUBLIC_API_URL}}/player
Content-Type: application/json

### 
# @name GET playes 
GET {{NEXT_PUBLIC_API_URL}}/player/{{playerId}}
Content-Type: application/json

### 
# @name GET playes stats 
GET {{NEXT_PUBLIC_API_URL}}/player/{{playerId}}/stats
Content-Type: application/json

### 
# @name update playes stats 
PUT {{NEXT_PUBLIC_API_URL}}/player/{{playerId}}/stats
Content-Type: application/json
Authorization: Bearer {{token}}

{ 
  "matches":3,
  "kills":15,
  "deaths":2,
  "wins":1
}

### 
# @name update playes stats 
POST {{NEXT_PUBLIC_API_URL}}/tournament
Content-Type: application/json
Authorization: Bearer {{token}}

{ 
  "name":"test 5",
  "fee":1
}

### 
# @name update playes stats 
GET {{NEXT_PUBLIC_API_URL}}/tournament/{{tournamentId}}/fixture
Content-Type: application/json
Authorization: Bearer {{token}}
